USE SCHEMA STG_DEMO ; 
CREATE TABLE IF NOT EXISTS T_FINANCIALS_PNL (
    COUNTRY_CODE varchar(150) NOT NULL PRIMARY KEY COMMENT 'Country code ',
    CALENDAR_MONTH integer NOT NULL COMMENT 'Month associated with sell in',
    SKU_CODE varchar(150) NOT NULL COMMENT 'RB SKU Code',
    RETAILER_ID varchar(150) NOT NULL COMMENT 'Retailer ID',
    CHANNEL_ID varchar(150) NOT NULL COMMENT 'ID of the Web, Store or Delivery- a place where the item was sold or the mechanism',
    BUSINESS_UNIT_ID varchar(150) NOT NULL COMMENT 'Business Unit description',
    CATEGORY_ID varchar(150) NOT NULL COMMENT 'Category description',
    NON_PROMO_TRADE_INVESTMENT decimal(22,4) COMMENT 'NON_PROMO_TRADE_INVESTMENT',
    YEAR integer NOT NULL COMMENT 'Custom Metric ID NAME as required for Channel-Category',
    SKU_DESCRIPTION varchar(150) COMMENT 'Custom Metric ID Value as required for Channel-Category',
    CURRENCY_ID varchar(150) COMMENT 'Custom Metric ID NAME as required for Channel-Category',
    TOTAL_UNITS decimal(22,4) COMMENT 'Custom Metric ID Value as required for Channel-Category',
    TOTAL_SALES decimal(22,4) COMMENT 'Custom Metric ID NAME as required for Channel-Category',
    TOTAL_CASES decimal(22,4) COMMENT 'Custom Metric ID Value as required for Channel-Category',
    GROSS_SALES_RESALES decimal(22,4) COMMENT 'Custom Metric ID NAME as required for Channel-Category',
    FREE_GOODS decimal(22,4) COMMENT 'Custom Metric ID Value as required for Channel-Category',
    GROSS_REVENUE decimal(22,4) COMMENT 'Custom Metric ID NAME as required for Channel-Category',
    RETURNS decimal(22,4) COMMENT 'Custom Metric ID Value as required for Channel-Category',
    DISTRIBUTOR_MARGIN_TRADESPEND varchar(150) COMMENT 'Combination used to pull data form Fusion',
    ADDITIONAL_COLUMN decimal(22,4) COMMENT 'Combination used to pull data form Fusion'
);USE SCHEMA STG_DEMO ; 
CREATE TABLE IF NOT EXISTS T_TRANSACTIONAL_PNL (
    TRANSACTIONAL_DISCOUNTS decimal(22,4) COMMENT 'Additional Column',
    FREE_GOODS_UNCONDITIONAL decimal(22,4) COMMENT 'Year associated with sell in',
    QUANTITY_LOGISTICAL_DISCOUNTS decimal(22,4) COMMENT 'RB SKU Description',
    CASH_DISCOUNTS decimal(22,4) COMMENT 'RB SKU Description',
    UNCONDITIONAL_ALLOWANCE decimal(22,4) COMMENT 'Units sold',
    COND_PROMOTIONAL_DISCOUNTS decimal(22,4) COMMENT 'Volume Doses',
    STPRICE_REDUCTION decimal(22,4) COMMENT '212',
    EDLP_ALLOWANCES decimal(22,4) COMMENT '212',
    FREE_GOODS_CONDITIONAL decimal(22,4) COMMENT '212',
    PRICE_REDUCTIONS_ON_INVOICE decimal(22,4) COMMENT 'Gross Sales',
    COND_TRADE_DEVELOPMENT_REBATES decimal(22,4) COMMENT 'asdas',
    COND_CUSTOMER_SPECIFIC_COUPONS decimal(22,4) COMMENT 'asdas',
    COND_PLACEMENT_FEE decimal(22,4) COMMENT 'asdas',
    NEW_PRODUCT_LISTING_FEES decimal(22,4) COMMENT 'asdas',
    NEW_STORE_WAREHOUSE_OPENING decimal(22,4) COMMENT 'asdas',
    SHELF_PLACEMENT decimal(22,4) COMMENT 'asdas',
    ASSORTMENT_INCENTIVES decimal(22,4) COMMENT 'asdas',
    COND_INSTORE_PROMO decimal(22,4) COMMENT 'asdas',
    COND_ONLINE_PROMO_FEES decimal(22,4) COMMENT 'asdas',
    COND_ONLINE_PLACEMENT_FEES decimal(22,4) COMMENT 'asdas',
    NATIONAL_COUPONS decimal(22,4) COMMENT 'asdas',
    NET_REVENUE decimal(22,4) COMMENT 'asdas',
    TOTAL_NET_REVENUE_THIRD_PARTIES decimal(22,4) COMMENT 'asdas',
    GROSS_MARGIN decimal(22,4) COMMENT 'asdas',
    GROSS_MARGIN_COMMERCIAL decimal(22,4) COMMENT 'asdas',
    TRANSACTION_PRICE decimal(22,4) COMMENT 'asdas',
    TRADE_INVESTMENT decimal(22,4) COMMENT 'asdas',
    VARIABLE_TRADE_PROMOTION decimal(22,4) COMMENT 'asdas',
    TOTAL_COGS_THIRD_PARTIES decimal(22,4) COMMENT 'asdas',
    CUSTOMER_SPECIFIC_COUPONS decimal(22,4) COMMENT 'asdas',
    TI_EXCL_MOON_PRICING_INCL_COUPONS decimal(22,4) COMMENT 'asdas',
    MOON_PRICING decimal(22,4) COMMENT 'asdas',
    COST_METRIC_1_ID varchar(150) COMMENT 'Coupons',
    COST_METRIC_1 decimal(22,4) COMMENT 'Net Sales',
    COST_METRIC_2_ID varchar(150) COMMENT 'Net Sales',
    COST_METRIC_2 decimal(22,4) COMMENT 'Gross Margin',
    COST_METRIC_3_ID varchar(150) COMMENT 'Gross Margin',
    COST_METRIC_3 varchar(200) COMMENT 'Gross Margin',
    COST_METRIC_4_ID varchar(150) COMMENT 'Investment',
    COST_METRIC_4 decimal(22,4) COMMENT 'Investment',
    COST_METRIC_5_ID varchar(200) COMMENT 'COGS',
    COST_METRIC_5 decimal(22,4) COMMENT 'COGS',
    COST_METRIC_6 decimal(22,4) COMMENT 'New column Metric 6'
);